linters:
  disable-all: true
  enable:
    - asciicheck
    - decorder
    - dupl
    - dupword
    - durationcheck
    - forcetypeassert
    - goconst
    - godot
    - gofmt
    - goheader
    - gosimple
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - nlreturn
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - wsl

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - dupl

linters-settings:
  nestif:
    min-complexity: 10

  goheader:
    values:
      const:
        COMPANY: SGNL.ai, Inc.
    template: Copyright {{ YEAR }} {{ COMPANY }}
